services:
  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=petcare
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
